version: "3.5"
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/prometheus"
services:
  software:
    image: prom/prometheus
    networks:
      - internal
    environment:
    volumes:
      - data/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host: prometheus.leejonchapman.com"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.docker.network: "internal"
        traefik.port: 9090 
      placement:
        constraints:
          - node.role == worker
      mode: global   
networks:
  internal:
    name: internal
    external: true
