version: "3.5"
services:
  software:
    image: prom/prometheus
    networks:
      - internal
    secrets:
      - source: config
        target: /etc/prometheus/prometheus.yml
        mode: 0666
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host: prometheus.leejonchapman.com"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.docker.network: "internal"
        traefik.port: 9090
      placement:
        constraints:
          - node.role == worker
      mode: global
secrets:
  config:
    file: prometheus.yaml
networks:
  internal:
    name: internal
    external: true
